package sv.edu.ues.fia.minedashboard;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

/**
 * Created by Enrique Lara on 15/06/2017.
 */

public class ControlDB extends SQLiteOpenHelper {
    public ControlDB(Context context, String name, SQLiteDatabase.CursorFactory factory, int version) {
        super(context, name, factory, version);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
       //creación de Tablas de Departamento y municipio
        db.execSQL("CREATE TABLE Departamento (id_depto VARCHAR(4) PRIMARY KEY  NOT NULL , nombre TEXT);");
        db.execSQL("CREATE TABLE Municipio (id_mun VARCHAR(4) PRIMARY KEY  NOT NULL , nombre TEXT, id_depto VARCHAR(4));");

        //Inserción de datos en la tabla Departamento
        db.execSQL("INSERT INTO Departamento VALUES('0000','Nacional');");
        db.execSQL("INSERT INTO Departamento VALUES('0001','Ahuachapán');");
        db.execSQL("INSERT INTO Departamento VALUES('0002','Santa Ana');");
        db.execSQL("INSERT INTO Departamento VALUES('0003','Sonsonate');");
        db.execSQL("INSERT INTO Departamento VALUES('0004','Chalatenango');");
        db.execSQL("INSERT INTO Departamento VALUES('0005','La Libertad');");
        db.execSQL("INSERT INTO Departamento VALUES('0006','San Salvador');");
        db.execSQL("INSERT INTO Departamento VALUES('0007','Cuscatlán');");
        db.execSQL("INSERT INTO Departamento VALUES('0008','La Paz');");
        db.execSQL("INSERT INTO Departamento VALUES('0009','Cabañas');");
        db.execSQL("INSERT INTO Departamento VALUES('0010','San Vicente');");
        db.execSQL("INSERT INTO Departamento VALUES('0011','Usulután');");
        db.execSQL("INSERT INTO Departamento VALUES('0012','San Miguel');");
        db.execSQL("INSERT INTO Departamento VALUES('0013','Morazán');");
        db.execSQL("INSERT INTO Departamento VALUES('0014','La Unión');");

        //Inserción de datos en la tabla Municipio
        db.execSQL("INSERT INTO Municipio VALUES('0000','---','0000');");
        db.execSQL("INSERT INTO Municipio VALUES('0100','---','0001');");
        db.execSQL("INSERT INTO Municipio VALUES('0101','Ahuachapán','0001');");
        db.execSQL("INSERT INTO Municipio VALUES('0102','Apaneca','0001');");
        db.execSQL("INSERT INTO Municipio VALUES('0103','Atiquizaya','0001');");
        db.execSQL("INSERT INTO Municipio VALUES('0104','Concepcón de Ataco','0001');");
        db.execSQL("INSERT INTO Municipio VALUES('0105','El Refugio','0001');");
        db.execSQL("INSERT INTO Municipio VALUES('0106','Guaymango','0001');");
        db.execSQL("INSERT INTO Municipio VALUES('0107','Jujutla','0001');");
        db.execSQL("INSERT INTO Municipio VALUES('0108','San Francisco Menéndez','0001');");
        db.execSQL("INSERT INTO Municipio VALUES('0109','San Lorenzo','0001');");
        db.execSQL("INSERT INTO Municipio VALUES('0110','San Pedro Puxtla','0001');");
        db.execSQL("INSERT INTO Municipio VALUES('0111','Tacuba','0001');");
        db.execSQL("INSERT INTO Municipio VALUES('0112','Turín','0001');");
        db.execSQL("INSERT INTO Municipio VALUES('0200','---','0002');");
        db.execSQL("INSERT INTO Municipio VALUES('0201','Candelaria de la Frontera','0002');");
        db.execSQL("INSERT INTO Municipio VALUES('0202','Coatepeque','0002');");
        db.execSQL("INSERT INTO Municipio VALUES('0203','Chalchuapa','0002');");
        db.execSQL("INSERT INTO Municipio VALUES('0204','El Congo','0002');");
        db.execSQL("INSERT INTO Municipio VALUES('0205','El Porvenir','0002');");
        db.execSQL("INSERT INTO Municipio VALUES('0206','Masahuat','0002');");
        db.execSQL("INSERT INTO Municipio VALUES('0207','Metapán','0002');");
        db.execSQL("INSERT INTO Municipio VALUES('0208','San Antonio Pajonal','0002');");
        db.execSQL("INSERT INTO Municipio VALUES('0209','San Sebastián Salitrillo','0002');");
        db.execSQL("INSERT INTO Municipio VALUES('0210','Santa Ana','0002');");
        db.execSQL("INSERT INTO Municipio VALUES('0211','Santa Rosa Guachipilín','0002');");
        db.execSQL("INSERT INTO Municipio VALUES('0212','Santiago de la Frontera','0002');");
        db.execSQL("INSERT INTO Municipio VALUES('0213','Texistepeque','0002');");
        db.execSQL("INSERT INTO Municipio VALUES('0300','---','0003');");
        db.execSQL("INSERT INTO Municipio VALUES('0301','Acajutla','0003');");
        db.execSQL("INSERT INTO Municipio VALUES('0302','Armenia','0003');");
        db.execSQL("INSERT INTO Municipio VALUES('0303','Caluco','0003');");
        db.execSQL("INSERT INTO Municipio VALUES('0304','Cuisnahuat','0003');");
        db.execSQL("INSERT INTO Municipio VALUES('0305','Santa Isabel Ishuatán','0003');");
        db.execSQL("INSERT INTO Municipio VALUES('0306','Izalco','0003');");
        db.execSQL("INSERT INTO Municipio VALUES('0307','Juayúa','0003');");
        db.execSQL("INSERT INTO Municipio VALUES('0308','Nahuizalco','0003');");
        db.execSQL("INSERT INTO Municipio VALUES('0309','Nahuilingo','0003');");
        db.execSQL("INSERT INTO Municipio VALUES('0310','Salcoatitán','0003');");
        db.execSQL("INSERT INTO Municipio VALUES('0311','San Antonio del Monte','0003');");
        db.execSQL("INSERT INTO Municipio VALUES('0312','San Julián','0003');");
        db.execSQL("INSERT INTO Municipio VALUES('0313','Santa Catarina Masahuat','0003');");
        db.execSQL("INSERT INTO Municipio VALUES('0314','Santo Domingo de Guzmán','0003');");
        db.execSQL("INSERT INTO Municipio VALUES('0315','Sonsonate','0003');");
        db.execSQL("INSERT INTO Municipio VALUES('0316','Sonzacate','0003');");
        db.execSQL("INSERT INTO Municipio VALUES('0400','---','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0401','Agua Caliente','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0402','Arcatao','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0403','Azacualpa','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0404','Citalá','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0405','Comalapa','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0406','Concepción Quezaltepeque','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0407','Chalatenango','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0408','Dulce Nombre de María','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0409','El Carrizal','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0410','El Paraíso','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0411','La Laguna','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0412','La Palma','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0413','La Reina','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0414','Las Vueltas','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0415','Nombre de Jesús','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0416','Nueva Concepción','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0417','Nueva Trinidad','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0418','Ojos de Agua','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0419','Potonico','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0420','San Antonio de la Cruz','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0421','San Antonio de los Ranchos','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0422','San Fernando','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0423','San Francisco Lempa','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0424','San Francisco Morazán','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0425','San Ignacio','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0426','San Isidro Labrador','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0427','San José Cancasque','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0428','San Jose Las Flores','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0429','San Luis del Carmen','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0430','San Miguel de Mercedes','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0431','San Rafael','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0432','Santa Rita','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0433','Tejutla','0004');");
        db.execSQL("INSERT INTO Municipio VALUES('0500','---','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0501','Antiguo Cuscatlán','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0502','Ciudad Arce','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0503','Colón','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0504','Comasagua','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0505','Chiltiupán','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0506','Huizúcar','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0507','Jayaque','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0508','Jicalapa','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0509','La Libertad','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0510','Nuevo Cuscatlán','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0511','Santa Tecla','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0512','Quezaltepeque','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0513','Sacacoyo','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0514','San José Villanueva','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0515','San Juan Opico','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0516','San Matías','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0517','San Pablo Tacachico','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0518','Tamanique','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0519','Talnique','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0520','Teotepeque','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0521','Tepecoyo','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0522','Zaragoza','0005');");
        db.execSQL("INSERT INTO Municipio VALUES('0600','---','0006');");
        db.execSQL("INSERT INTO Municipio VALUES('0601','Aguilares','0006');");
        db.execSQL("INSERT INTO Municipio VALUES('0602','Apopa','0006');");
        db.execSQL("INSERT INTO Municipio VALUES('0603','Ayutuxtepeque','0006');");
        db.execSQL("INSERT INTO Municipio VALUES('0604','Cuscatancingo','0006');");
        db.execSQL("INSERT INTO Municipio VALUES('0605','El Paisnal','0006');");
        db.execSQL("INSERT INTO Municipio VALUES('0606','Guazapa','0006');");
        db.execSQL("INSERT INTO Municipio VALUES('0607','Ilopango','0006');");
        db.execSQL("INSERT INTO Municipio VALUES('0608','Mejicanos','0006');");
        db.execSQL("INSERT INTO Municipio VALUES('0609','Nejapa','0006');");
        db.execSQL("INSERT INTO Municipio VALUES('0610','Panchimalco','0006');");
        db.execSQL("INSERT INTO Municipio VALUES('0611','Rosario de Mora','0006');");
        db.execSQL("INSERT INTO Municipio VALUES('0612','San Marcos','0006');");
        db.execSQL("INSERT INTO Municipio VALUES('0613','San Martín','0006');");
        db.execSQL("INSERT INTO Municipio VALUES('0614','San Salvador','0006');");
        db.execSQL("INSERT INTO Municipio VALUES('0615','Santiago Texacuangos','0006');");
        db.execSQL("INSERT INTO Municipio VALUES('0616','Santo Tomás','0006');");
        db.execSQL("INSERT INTO Municipio VALUES('0617','Soyapango','0006');");
        db.execSQL("INSERT INTO Municipio VALUES('0618','Tonacatepeque','0006');");
        db.execSQL("INSERT INTO Municipio VALUES('0619','Ciudad Delgado','0006');");
        db.execSQL("INSERT INTO Municipio VALUES('0700','---','0007');");
        db.execSQL("INSERT INTO Municipio VALUES('0701','Candelaria','0007');");
        db.execSQL("INSERT INTO Municipio VALUES('0702','Cojutepeque','0007');");
        db.execSQL("INSERT INTO Municipio VALUES('0703','El Carmen','0007');");
        db.execSQL("INSERT INTO Municipio VALUES('0704','El Rosario','0007');");
        db.execSQL("INSERT INTO Municipio VALUES('0705','Monte San Juan','0007');");
        db.execSQL("INSERT INTO Municipio VALUES('0706','Oratorio de Concepción','0007');");
        db.execSQL("INSERT INTO Municipio VALUES('0707','San Bartolomé Perulapía','0007');");
        db.execSQL("INSERT INTO Municipio VALUES('0708','San Cristóbal','0007');");
        db.execSQL("INSERT INTO Municipio VALUES('0709','San José Guayabal','0007');");
        db.execSQL("INSERT INTO Municipio VALUES('0710','San Pedro Perulapán','0007');");
        db.execSQL("INSERT INTO Municipio VALUES('0711','San Rafael Cedros','0007');");
        db.execSQL("INSERT INTO Municipio VALUES('0712','San Ramón','0007');");
        db.execSQL("INSERT INTO Municipio VALUES('0713','Santa Cruz Analquito','0007');");
        db.execSQL("INSERT INTO Municipio VALUES('0714','Santa Cruz Michapa','0007');");
        db.execSQL("INSERT INTO Municipio VALUES('0715','Suchitoto','0007');");
        db.execSQL("INSERT INTO Municipio VALUES('0716','Tenancingo','0007');");
        db.execSQL("INSERT INTO Municipio VALUES('0800','---','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0801','Cuyultitán','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0802','El Rosario','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0803','Jerusalén','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0804','Mercedes La Ceiba','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0805','Olocuilta','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0806','Paraíso de Osorio','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0807','San Antonio Masahuat','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0808','San Emigdio','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0809','San Francisco Chinameca','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0810','San Juan Nonualco','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0811','San Juan Talpa','0008')");
        db.execSQL("INSERT INTO Municipio VALUES('0812','San Juan Tepezontes','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0813','San Luis Talpa','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0814','San Miguel Tepezontes','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0815','San Pedro Masahuat','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0816','San Pedro Nonualco','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0817','San Rafael Obrajuelo','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0818','Santa María Ostuma','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0819','Santiago Nonualco','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0820','Tapalhuaca','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0821','Zacatecoluca','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0822','San Luis La Herradura','0008');");
        db.execSQL("INSERT INTO Municipio VALUES('0900','---','0009');");
        db.execSQL("INSERT INTO Municipio VALUES('0901','Cinquera','0009');");
        db.execSQL("INSERT INTO Municipio VALUES('0902','Guacotecti','0009');");
        db.execSQL("INSERT INTO Municipio VALUES('0903','Ilobasco','0009');");
        db.execSQL("INSERT INTO Municipio VALUES('0904','Jutiapa','0009');");
        db.execSQL("INSERT INTO Municipio VALUES('0905','San Isidro','0009');");
        db.execSQL("INSERT INTO Municipio VALUES('0906','Sensuntepeque','0009');");
        db.execSQL("INSERT INTO Municipio VALUES('0907','Tejutepeque','0009');");
        db.execSQL("INSERT INTO Municipio VALUES('0908','Victoria','0009');");
        db.execSQL("INSERT INTO Municipio VALUES('0909','Dolores','0009');");
        db.execSQL("INSERT INTO Municipio VALUES('1000','---','0010');");
        db.execSQL("INSERT INTO Municipio VALUES('1001','Apastepeque','0010');");
        db.execSQL("INSERT INTO Municipio VALUES('1002','Guadalupe','0010');");
        db.execSQL("INSERT INTO Municipio VALUES('1003','San Cayetano Istepeque','0010');");
        db.execSQL("INSERT INTO Municipio VALUES('1004','Santa Clara','0010');");
        db.execSQL("INSERT INTO Municipio VALUES('1005','Santo Domingo','0010');");
        db.execSQL("INSERT INTO Municipio VALUES('1006','San Esteban Catarina','0010');");
        db.execSQL("INSERT INTO Municipio VALUES('1007','San Ildefonso','0010');");
        db.execSQL("INSERT INTO Municipio VALUES('1008','San Lorenzo','0010');");
        db.execSQL("INSERT INTO Municipio VALUES('1009','San Sebastián','0010');");
        db.execSQL("INSERT INTO Municipio VALUES('1010','San Vicente','0010');");
        db.execSQL("INSERT INTO Municipio VALUES('1011','Tecoluca','0010');");
        db.execSQL("INSERT INTO Municipio VALUES('1012','Tepetitán','0010');");
        db.execSQL("INSERT INTO Municipio VALUES('1013','Verapaz','0010');");
        db.execSQL("INSERT INTO Municipio VALUES('1100','---','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1101','Alegría','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1102','Berlín','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1103','California','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1104','Concepción Batres','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1105','Ciudad El Triunfo','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1106','Ereguayquín','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1107','Estanzuelas','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1108','Jiquilisco','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1109','Jucuapa','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1110','Jucuarán','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1111','Mercedes Umaña','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1112','Nueva Granada','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1113','Ozatlán','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1114','Puerto El Triunfo','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1115','San Agustín','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1116','San Buenaventura','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1117','San Dionisio','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1118','Santa Elena','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1119','San Francisco Javier','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1120','Santa María','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1121','Santiago de María','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1122','Tecapán','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1123','Usulután','0011');");
        db.execSQL("INSERT INTO Municipio VALUES('1200','---','0012');");
        db.execSQL("INSERT INTO Municipio VALUES('1201','Carolina','0012');");
        db.execSQL("INSERT INTO Municipio VALUES('1202','Ciudad Barrios','0012');");
        db.execSQL("INSERT INTO Municipio VALUES('1203','Comacarán','0012');");
        db.execSQL("INSERT INTO Municipio VALUES('1204','Chapeltique','0012');");
        db.execSQL("INSERT INTO Municipio VALUES('1205','Chinameca','0012');");
        db.execSQL("INSERT INTO Municipio VALUES('1206','Chirilagua','0012');");
        db.execSQL("INSERT INTO Municipio VALUES('1207','El Tránsito','0012');");
        db.execSQL("INSERT INTO Municipio VALUES('1208','Lolotique','0012');");
        db.execSQL("INSERT INTO Municipio VALUES('1209','Moncagua','0012');");
        db.execSQL("INSERT INTO Municipio VALUES('1210','Nueva Guadalupe','0012');");
        db.execSQL("INSERT INTO Municipio VALUES('1211','Nuevo Edén de San Juan','0012');");
        db.execSQL("INSERT INTO Municipio VALUES('1212','Quelepa','0012');");
        db.execSQL("INSERT INTO Municipio VALUES('1213','San Antonio','0012');");
        db.execSQL("INSERT INTO Municipio VALUES('1214','San Gerardo','0012');");
        db.execSQL("INSERT INTO Municipio VALUES('1215','San Jorge','0012');");
        db.execSQL("INSERT INTO Municipio VALUES('1216','San Luis de La Reina','0012');");
        db.execSQL("INSERT INTO Municipio VALUES('1217','San Miguel','0012');");
        db.execSQL("INSERT INTO Municipio VALUES('1218','San Rafael Oriente','0012');");
        db.execSQL("INSERT INTO Municipio VALUES('1219','Sesori','0012');");
        db.execSQL("INSERT INTO Municipio VALUES('1220','Uluazapa','0012');");
        db.execSQL("INSERT INTO Municipio VALUES('1300','---','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1301','Arambala','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1302','Cacaopera','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1303','Corinto','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1304','Chilanga','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1305','Delicias de Concepción','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1306','El Divisadero','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1307','El Rosario','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1308','Gualococti','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1309','Guatajiagua','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1310','Joateca','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1311','Jocoaitique','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1312','Jocoro','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1313','Lolotiquillo','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1314','Menaguera','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1315','Osicala','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1316','Perquín','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1317','San Carlos','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1318','San Fernando','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1319','San Francisco Gotera','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1320','San Isidro','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1321','San Simón','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1322','Sensembra','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1323','Sociedad','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1324','Torola','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1325','Yamabal','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1326','Yoloaquín','0013');");
        db.execSQL("INSERT INTO Municipio VALUES('1400','---','0014');");
        db.execSQL("INSERT INTO Municipio VALUES('1401','Anamorós','0014');");
        db.execSQL("INSERT INTO Municipio VALUES('1402','Bolívar','0014');");
        db.execSQL("INSERT INTO Municipio VALUES('1403','Concepción de Oriente','0014');");
        db.execSQL("INSERT INTO Municipio VALUES('1404','Conchagua','0014');");
        db.execSQL("INSERT INTO Municipio VALUES('1405','El Carmen','0014');");
        db.execSQL("INSERT INTO Municipio VALUES('1406','El Sauce','0014');");
        db.execSQL("INSERT INTO Municipio VALUES('1407','Intipucá','0014');");
        db.execSQL("INSERT INTO Municipio VALUES('1408','La Unión','0014');");
        db.execSQL("INSERT INTO Municipio VALUES('1409','Lislique','0014');");
        db.execSQL("INSERT INTO Municipio VALUES('1410','Meanguera del Golfo','0014');");
        db.execSQL("INSERT INTO Municipio VALUES('1411','Nueva Esparta','0014');");
        db.execSQL("INSERT INTO Municipio VALUES('1412','Pasaquina','0014');");
        db.execSQL("INSERT INTO Municipio VALUES('1413','Polorós','0014');");
        db.execSQL("INSERT INTO Municipio VALUES('1414','San Alejo','0014');");
        db.execSQL("INSERT INTO Municipio VALUES('1415','San José','0014');");
        db.execSQL("INSERT INTO Municipio VALUES('1416','Santa Rosa de Lima','0014');");
        db.execSQL("INSERT INTO Municipio VALUES('1417','Yayantique','0014');");
        db.execSQL("INSERT INTO Municipio VALUES('1418','Yucuaiquín','0014');");
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {

    }
}
